# First print your name in the cell below then save this file. (or something nice about your instructor)

In [ ]:
# In this cell print your name 
print("Lhakpa K Sherpa")

Lhakpa K Sherpa

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [16]:
# Load data here
import pandas as pd

df = pd.read_csv("../data/listings.csv")

print(df)

             id                                               name    host_id  \
0          2595                              Skylit Midtown Castle       2845
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...       4869
2          5121                                    BlissArtsSpace!       7356
3          5136           Spacious Brooklyn Duplex, Patio + Garden       7378
4          5178                   Large Furnished Room Near B'way　       8967
...         ...                                                ...        ...
46522  44807522         Designer Gramercy Studio Townhouse by UNSQ   12941925
46523  44807786  Cozy & comfy apt in the heart of Inwood Manhattan  284790520
46524  44811717  Comfortable safe environment 24hr security camera  362453686
46525  44814944                 Upper West Side studio 86th Street    4039777
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN   48098268

         host_name neighbourhood_group       neighbourhood  latitude  \
0         Jennifer           Manhattan             Midtown  40.75362
1      LisaRoxanne            Brooklyn        Clinton Hill  40.68514
2            Garon            Brooklyn  Bedford-Stuyvesant  40.68688
3          Rebecca            Brooklyn         Sunset Park  40.66120
4         Shunichi           Manhattan      Hell's Kitchen  40.76489
...            ...                 ...                 ...       ...
46522        Brian           Manhattan            Gramercy  40.73433
46523        Salar           Manhattan  Washington Heights  40.85820
46524       Nicole            Brooklyn       East Flatbush  40.65399
46525     Fernando           Manhattan     Upper West Side  40.78731
46526       Marina            Brooklyn           Gravesend  40.59945

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.98377  Entire home/apt    175               3                 48
1      -73.95976  Entire home/apt     75               1                340
2      -73.95596     Private room     60              29                 50
3      -73.99423  Entire home/apt    175              14                  1
4      -73.98493     Private room     65               2                473
...          ...              ...    ...             ...                ...
46522  -73.98383  Entire home/apt    145               7                  0
46523  -73.92733  Entire home/apt     87               6                  0
46524  -73.93287     Private room     59               3                  0
46525  -73.97029  Entire home/apt     80              30                  0
46526  -73.98209     Private room     66               1                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
0      2019-11-04               0.37                               2
1      2020-08-01               4.75                               1
2      2019-12-02               0.37                               1
3      2014-01-02               0.01                               1
4      2020-03-15               3.44                               1
...           ...                ...                             ...
46522         NaN                NaN                               1
46523         NaN                NaN                               2
46524         NaN                NaN                               1
46525         NaN                NaN                               1
46526         NaN                NaN                               1

       availability_365
0                   365
1                   265
2                   365
3                   295
4                   340
...                 ...
46522               164
46523                85
46524                90
46525               113
46526                38

[46527 rows x 16 columns]

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [20]:
# 1. How many listings are there with a price less than 100? 

df[df["price"] < 100].shape[0]

22778

In [21]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

df_bk = df[df["neighbourhood_group"]=="Brooklyn"]
df_bk.shape[0]

18632

In [24]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
# 3. Find how many listings there are in Brooklyn with a price less than 100.

df_bk = df[df["neighbourhood_group"] == "Brooklyn"]

df_bk_under100 = df_bk[df_bk["price"] < 100]

print(df_bk_under100.shape[0])

10473

In [25]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names

names=["Michael", "David", "John","Daniel"]
df_names= df[df["host_name"].isin(names)]
print(df_names.shape[0])

1258

In [26]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

df["adjusted_price"] = df["price"]

df.loc[df["neighbourhood"] == "Williamsburg", "adjusted_price"] += 100

In [27]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

room_percent = df["room_type"].value_counts(normalize=True) * 100

print("Private rooms:", room_percent["Private room"], "%")
print("Shared rooms:", room_percent["Shared room"], "%")

Private rooms: 45.444580566122895 %
Shared rooms: 2.12134889419047 %

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [28]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

df.groupby("neighbourhood_group").size()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [ ]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

df.groupby("neighbourhood_group")["price"].mean()

In [29]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
df.groupby("room_type")["price"].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [30]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


df.groupby("neighbourhood_group")["price"].agg(["min", "max"])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [31]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.

df.groupby(["neighbourhood_group", "room_type"])["price"].mean()

neighbourhood_group  room_type
Bronx                Entire home/apt    138.004819
                     Private room        68.419668
                     Shared room         66.391304
Brooklyn             Entire home/apt    171.587687
                     Hotel room         147.300000
                     Private room        71.291189
                     Shared room         57.870091
Manhattan            Entire home/apt    231.335572
                     Hotel room         292.515670
                     Private room       128.277069
                     Shared room        111.735084
Queens               Entire home/apt    150.168900
                     Hotel room         139.058824
                     Private room        69.972564
                     Shared room         89.891892
Staten Island        Entire home/apt    151.720930
                     Private room        70.312883
                     Shared room         46.000000
Name: price, dtype: float64

In [32]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

df.groupby(["neighbourhood_group", "room_type"])["price"].agg(
    ["count", "min", "max", "mean", "median", "std"]
)

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.004819   103.0
                    Private room       722   16    700   68.419668    55.0
                    Shared room         46   20    800   66.391304    44.0
Brooklyn            Entire home/apt   9112   20  10000  171.587687   135.0
                    Hotel room          30    0    399  147.300000   129.0
                    Private room      9159   10   2500   71.291189    60.0
                    Shared room        331   15   1500   57.870091    36.0
Manhattan           Entire home/apt  12209    0  10000  231.335572   165.0
                    Hotel room         351    0   2211  292.515670   210.0
                    Private room      7601   10  10000  128.277069    80.0
                    Shared room        419   10  10000  111.735084    60.0
Queens              Entire home/apt   2090   10  10000  150.168900   115.0
                    Hotel room          17    0    249  139.058824   149.0
                    Private room      3499   18   9000   69.972564    55.0
                    Shared room        185   14   3000   89.891892    40.0
Staten Island       Entire home/apt    172   39   1200  151.720930   111.0
                    Private room       163   20    800   70.312883    55.0
                    Shared room          6   19     82   46.000000    38.0

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [33]:
# 1. Load the `prices.csv` and the `n_listings.csv`
import pandas as pd

prices = pd.read_csv("../data/prices.csv")
n_listings = pd.read_csv("../data/n_listings.csv")

In [39]:
# 2. Do join that keeps all the records for each table.

df_joined = prices.merge(
    n_listings,
    on="neighbourhood_group",
    how="outer"
)
df_joined

KeyError: 'neighbourhood_group'

In [35]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
df_joined.to_csv("../data/joined.csv", index=False)

NameError: name 'df_joined' is not defined

In [40]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
joined = pd.read_csv("../data/joined.csv")

joined

FileNotFoundError: [Errno 2] No such file or directory: '../data/joined.csv'

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.